### DISCUSSION TITLE
Bogon filters and polices in JUNIPER

### DISCUSSION THREAD

**Discussion by jorgewallace** [thatmattlove/hyperglass#265] [Q&A]
Case 01 - 

Sorry for my English, I'm using a translator. I need help in a scenario when creating my own directives.yaml for Juniper, I am not shown the standard hyperglass formatting. To use the default I need to leave the :
```
   directives:
    - builtins: [bgp_route]
    - Juniper_Ping
    - Juniper_Traceroute
```

And with that I can't do the bogons network filters. Has anyone ever experienced this? There is a middle ground, where I can apply the filters in the standard directives or I can use my own directives with the standard output

![image](https://github.com/thatmattlove/hyperglass/assets/81370147/e9f31916-972d-41cb-a45f-4a1bdba6c6ef)
![image](https://github.com/thatmattlove/hyperglass/assets/81370147/bbe6d7be-9f96-4421-b226-07202f4ea3df)

Case -02 
When filtering, the output should look like version 1.0.4: 10.254.32.0/24 is a member of 10.0.0.0/8, which is not allowed
![image](https://github.com/thatmattlove/hyperglass/assets/81370147/82fd5f6d-ab36-4eda-92f2-45a0df6d91a4)

But I have the answer:
Something went wrong. In version 2.0.2

![image](https://github.com/thatmattlove/hyperglass/assets/81370147/9bad2992-3608-42fc-8bdf-ab9cbf6e414f)

**Comment by jdhall75** [comment]
@jorgewallace did you ever figure this out?  Here is an example of a bogon filter for a custom directive

```yaml
my_ping:
  name: Ping
  rules:
    - condition: 10.0.0.0/8
      action: deny
    - condition: 172.16.0.0/12
      action: deny
    - condition: 192.168.0.0/16
      action: deny
    - condition: 0.0.0.0/8
      action: deny
    - condition: 100.64.0.0/10
      action: deny
    - condition: 127.0.0.0/8
      action: deny
    - condition: 169.254.0.0/16
      action: deny
    - condition: 192.0.2.0/24
      action: deny
    - condition: 192.88.99.0/24
      action: deny
    - condition: 198.18.0.0/15
      action: deny
    - condition: 198.51.100.0/24
      action: deny
    - condition: 203.0.113.0/24
      action: deny
    - condition: 224.0.0.0/4
      action: deny
    - condition: 240.0.0.0/4
      action: deny
    - condition: 0.0.0.0/0
      action: permit
      command: ping {target} source {source4} no-resolve wait 1 count 4
  field:
    description: IP Address or hostname to ping
```
