### ISSUE TITLE
New links get the same address as peeringdb

### ISSUE THREAD

**Issue by pcfriek1987** [thatmattlove/hyperglass#145]
I added the peeringdb link on the left which works fine, but also tried adding a second link on the right, which still has the peeringdb link even though it has a different value.

  links:
    - order: 0
      show_icon: true
      side: left
      title: PeeringDB
      url: https://www.peeringdb.com/asn/{primary_asn}
    - order: 5
      side: right
      title: Website
      url: https://google.com

I replaced the website with a generic one since this is my private github account :)

**Comment by checktheroads** [comment]
Hmm, I'm not able to reproduce this. My config:

```yaml
web:
    links:
        - title: PeeringDB
          order: 2
          url: https://peeringdb.com
        - title: Another Link
          order: 1
          url: https://www.google.com
          side: right
        - title: Yet Another Link
          order: 3
          url: https://www.cloudflare.com
          show_icon: false
```

When I have that in my config and start hyperglass (with `--build-ui` or `-b`), I see the links with the correct URLs. Can you try running `hyperglass build-ui` manually and see if that makes a difference?
