### ISSUE TITLE
SyntaxError: /tmp/hyperglass_XXX.json: Unexpected end of JSON input

### ISSUE THREAD

**Issue by ethamitc** [thatmattlove/hyperglass#152]
# Bug Description

Whenever I try to build the ui with `hyperglass build-ui`  it errors out giving the error `SyntaxError: /tmp/hyperglass_XXX.json: Unexpected end of JSON input`

# Expected behavior

I expect it to build the UI without any issue.

# Steps to Reproduce

- Install hyperglass using pip3
- Create devices.yaml file
- Run `hyperglass build-ui`

## Local Configurations

devices.yaml
```
routers:
  - name: rtr.fra.vtr.as211167.net
    address: REDACTED
    network:
      name: production
      display_name: AS211167
    credential:
      username: REDACTED
      password: REDACTED
    port: 22
    nos: vyos
    vrfs:
      - name: global
        default: true
        ipv4:
          source_address: REDACTED
```

## Logs

```
❌ Error building UI:
Messages:

Errors:
> Build error occurred
SyntaxError: /tmp/hyperglass_7ounc0yp.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/python3.7/dist-packages/hyperglass/ui/next.config.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

# Possible Solution

# Environment

Debian 10 LXC container 2GB/2C

## Server

❕ Please copy & paste this table in your bug report:

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.3** |
| **hyperglass Path** | `/etc/hyperglass` |
| **Python Version** | `3.7.3` |
| **Platform Info** | `Linux-5.4.119-1-pve-x86_64-with-debian-10.10` |
| **CPU Info** | AMD Ryzen 5 3600 6-Core Processor |
| **Logical Cores** | `2` |
| **Physical Cores** | `6` |
| **Processor Speed** | 3.6014085GHz |
| **Total Memory** | 2.15 GB |
| **Memory Utilization** | 5.2% |
| **Total Disk Space** | 17.18 GB |
| **Disk Utilization** | 11.8% |

## Client

- OS & Version: Windows 10
- Browser: MS Edge (Chromium ver.)
