### ISSUE TITLE
Cannot Identify Image

### ISSUE THREAD

**Issue by developerdevice** [thatmattlove/hyperglass#169]
# Bug Description

The doc tells that supported formats are `.jpg`, `.jpeg`, `.png`, `.svg`, but when I configure the path of my logo the HyperGlass returns 

❌ Error building UI: cannot identify image file '/etc/hyperglass/logo.png'

The same occurs to `.svg`, `.jpg` and `.jpeg`

## Local Configurations

```
---
logo:
  dark:  /etc/hyperglass/logo.png
  light: /etc/hyperglass/logo.png
  favicon: /etc/hyperglass/logo.png
  height: null
  width: 100%
```

## Logs

```
[ERROR] 20211112 16:16:09 | hyperglass.util.frontend:401 | build_frontend → cannot identify image file '/etc/hyperglass/logo.png'
❌ Error building UI: cannot identify image file '/etc/hyperglass/logo.png'
```

# Environment

## Server

| Metric | Value |
| :----- | :---- |
| **hyperglass Version** | 1.0.4 |
| **hyperglass Path** | `/etc/hyperglass` |
| **Python Version** | `3.7.3` |
| **Node Version** | `14.18.1` |
| **Platform Info** | `Linux-4.19.0-17-amd64-x86_64-with-debian-10.11` |
| **CPU Info** | Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz |
| **Logical Cores** | `4` |
| **Physical Cores** | `4` |
| **Processor Speed** | `2.394GHz` |
| **Total Memory** | 7.81 GB |
| **Memory Utilization** | 12.1% |
| **Total Disk Space** | 50.99 GB |
| **Disk Utilization** | 14.1% |

## Client

- OS & Version: Fedora 35
- Browser: Chrome 95.0.4638.69 and Firefox 94.0
