### ISSUE TITLE
Bad Gateway error for any query type

### ISSUE THREAD

**Issue by dd1245** [thatmattlove/hyperglass#197]
# Bug Description

I've installed the latest hyperglass on ubuntu via the manual installation guide and had no errors. I've added a few routers from different vendors (Juniper and Huawei), but any query run on them just brings up 'Bad Gateway'. From what I can tell from a local tcpdump, no attempt is made to connect to the devices configured in the devices.yaml file.

# Expected behavior

Actioning a route table query, or ping should provide a result.

# Steps to Reproduce

Run any query, or any device configured. The 'Bad Gateway Error' will be displayed.

## Local Configurations

```
routers:
  - name: London1
    address: 172.16.10.2
    network:
      name: production
      display_name: ASX
    credential:
      username: user@test
      password: not-shown
    port: 22
    nos: juniper_junos
    vrfs:
      - name: global
        default: true
        ipv4:
          source_address: 172.16.10.2
          ipv6: null
```
## Logs

Hyperglass.log does not appear to show an error

# Environment

## Server

```
| Metric | Value |
| :----- | :---- |
| **hyperglass Version** | 1.0.4 |
| **hyperglass Path** | `/home/user1/hyperglass` |
| **Python Version** | `3.6.9` |
| **Node Version** | `14.19.1` |
| **Platform Info** | `Linux-5.4.0-1068-gcp-x86_64-with-Ubuntu-18.04-bionic` |
| **CPU Info** | Intel(R) Xeon(R) CPU @ 2.20GHz |
| **Logical Cores** | `2` |
| **Physical Cores** | `1` |
| **Processor Speed** | `2.200156GHz` |
| **Total Memory** | 4.12 GB |
| **Memory Utilization** | 12.3% |
| **Total Disk Space** | 33.12 GB |
| **Disk Utilization** | 13.5% |
```

## Client

- OS & Version: Ubuntu Linux 18.04
- Browser: Chrome
