### ISSUE TITLE
Add OpenBGPD

### ISSUE THREAD

**Issue by job** [thatmattlove/hyperglass#206]
### Manufacturer

OpenBSD

### Platform Name

OpenBGPD

### Commands

```
---
special_commands:
  ipv4_default:
    bgp_route: "bgpctl show rib inet {target}"
    bgp_aspath: "bgpctl show rib inet as {target}"
    bgp_community: "bgpctl show rib inet community {target}"
    ping: "ping {target}"
    traceroute: "traceroute {target}"
  ipv6_default:
    bgp_route: "bgpctl show rib inet6 {target}"
    bgp_aspath: "bgpctl show rib inet6 as {target}"
    bgp_community: "bgptl show rib inet6 community {target}"
    ping: "ping6 {target}"
    traceroute: "traceroute6 {target}"
```
