### ISSUE TITLE
Commands from commands.yaml aren't executed by HyperGlass

### ISSUE THREAD

**Issue by Skylighty** [thatmattlove/hyperglass#215]
# Bug Description

I've created 'commands.yaml' file in HyperGlass directory and tried to overwrite basic command executed by HyperGlass in every possible way presented in the 'Custom commands' documentation. None of them have worked.

# Expected behavior
We use mainly Juniper MX routers, so the setup NOS is 'juniper_junos'.
The ping command executed by HyperGlass, by default is "ping inet {target} count 5 source {source-ip from device}".
I want to change it to "ping {target} count 5 routing-instance {vrf}" yet after adding commands.yaml with proper commands none of them are being executed instead of the default ones.

# Steps to Reproduce
Fresh install of HyperGlass on Ubuntu 20.04.
Python3.6.15 installed from deadsnakes repo and alternatived as default.
Add devices.yaml. commands.yaml and hyperglass.yaml.
Asyncssh downgraded to 2.7.0 (was 2.13.0 - HyperGlass couldn't log in).

## Local Configurations
```
hyperglass.yaml

debug: false
developer_mode: false
org_name: Organisation Name
site_title: Org Hyperglass
primary_asn: <ASN>
site_description: "{org_name} Network Looking Glass"
site_keywords: [hyperglass, looking glass, routing, bgp]
request_timeout: 60
listen_address: "192.168.168.97"
listen_port: 8001
```
```
commands.yaml

---
command_name:
  ipv4_default:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
  ipv4_vpn:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
  ipv6_default:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
  ipv6_vpn:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
special_commands:
  ipv4_default:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
  ipv4_vpn:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
  ipv6_default:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
  ipv6_vpn:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
juniper_junos:
  ipv4_default:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
  ipv4_vpn:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
  ipv6_default:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
  ipv6_vpn:
    ping: ping {target} count 5 routing-instance {vrf}
    traceroute: traceroute {target} routing-instance {vrf}
    bgp_community: show route active-path {target}
    bgp_route: show route active-path {target}
    bgp_aspath: show route active-path {target} | match "AS path"
```
```
devices.yaml

---
routers:
  - name: City1 MX480
    address: <ip>
    commands: special_commands
    network:
      name: City1
      display_name: City1
    credential:
      username: user
      password: pass
    port: 22
    nos: juniper_junos
    vrfs:
      - name: <vrf>
        default: true
        ipv4:
          source_address: <src-ip>
        ipv6: null
  - name: City2 MX480
    address: <ip>
    commands: special_commands
    network:
      name: City2
      display_name: City2
    credential:
      username: user
      password: pass
    port: 22
    nos: juniper_junos
    vrfs:
      - name: <vrf>
        default: true 
        ipv4:
          source_address: <ip>
        ipv6: null

```

## Logs

```
[DEBUG] 20230110 14:00:22 | hyperglass.execution.drivers._construct:27 | __init__ → Constructing ping query for '1.1.1.1'
[DEBUG] 20230110 14:00:22 | hyperglass.execution.drivers._construct:111 | queries → Constructed query: ['ping inet 1.1.1.1 count 5 source <ip>']
[DEBUG] 20230110 14:00:22 | hyperglass.execution.drivers.ssh_scrapli:83 | collect → Connecting directly to City1 MX480
[INFO] 20230110 14:00:22 | scrapli.driver.base.base_driver:897 | _pre_open_closing_log → opening connection to '<ip>' on port '22'
[INFO] 20230110 14:00:22 | scrapli.driver.network.base_driver:327 | _process_acquire_priv → attempting to acquire 'exec' privilege level
[DEBUG] 20230110 14:00:22 | scrapli.driver.network.base_driver:147 | _determine_current_priv → determined current privilege level is one of '['exec']'
[DEBUG] 20230110 14:00:22 | scrapli.driver.network.base_driver:345 | _process_acquire_priv → determined current privilege level is target privilege level, no action needed
[INFO] 20230110 14:00:25 | scrapli.driver.base.base_driver:916 | _post_open_closing_log → connection to '<ip' on port '22' opened successfully
[DEBUG] 20230110 14:00:39 | hyperglass.execution.drivers.ssh_scrapli:124 | collect → Raw response for command "ping inet 1.1.1.1 count 5 source<ip>":

```

# Possible Solution

I absolutely don't know how to fix it, because when HyperGlass starts it shows me the commands config parsed to JSON. Yet when it starts up it logs "univerified config" which is caused, again - I don't know by what.

# Environment
Python3.6.15
libs:
```
aiocontextvars==0.2.2
aiofiles==0.6.0
aredis==1.1.8
async-generator==1.10
asyncssh==2.7.0
attrs==19.3.0
Automat==0.8.0
bcrypt==4.0.1
blessed==1.19.0
blinker==1.4
certifi==2019.11.28
cffi==1.15.1
chardet==3.0.4
click==7.1.2
cloud-init==22.4.2
colorama==0.4.3
command-not-found==0.3
commonmark==0.9.1
configobj==5.0.6
constantly==15.1.0
contextvars==2.4
cryptography==3.0
cssselect2==0.4.1
dataclasses==0.8
dbus-python==1.2.16
distro==1.8.0
distro-info===0.23ubuntu1
entrypoints==0.3
fastapi==0.63.0
favicons==0.0.9
future==0.18.2
gunicorn==20.1.0
h11==0.13.0
httpcore==0.12.3
httplib2==0.14.0
httptools==0.1.2
httpx==0.17.1
hyperglass==1.0.4
hyperlink==19.0.0
idna==2.8
immutables==0.19
importlib-metadata==1.5.0
importlib-resources==5.4.0
incremental==16.10.1
inquirer==2.8.0
Jinja2==2.10.1
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
loguru==0.5.3
lxml==4.9.2
MarkupSafe==1.1.0
more-itertools==4.2.0
netifaces==0.10.4
netmiko==3.4.0
ntc-templates==3.1.0
oauthlib==3.1.0
paramiko==2.12.0
pexpect==4.6.0
Pillow==7.2.0
psutil==5.9.4
py-cpuinfo==7.0.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.21
pydantic==1.9.2
Pygments==2.14.0
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==2.4.0
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.0+ubuntu0.20.4.8
python-debian===0.1.36ubuntu1
python-dotenv==0.20.0
python-editor==1.0.4
PyYAML==5.4.1
readchar==2.0.1
redis==3.5.3
reportlab==3.6.8
requests==2.22.0
requests-unixsocket==0.2.0
rfc3986==1.5.0
rich==8.0.0
scp==0.14.4
scrapli==2021.7.30
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
sniffio==1.2.0
sos==4.4
ssh-import-id==5.10
starlette==0.13.6
svglib==1.1.0
systemd-python==234
tenacity==8.1.0
textfsm==1.1.3
tinycss2==1.1.1
Twisted==18.9.0
typer==0.3.2
typing-extensions==4.1.1
ubuntu-advantage-tools==27.12
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
uvicorn==0.13.4
uvloop==0.14.0
wadllib==1.3.3
watchgod==0.7
wcwidth==0.2.5
webencodings==0.5.1
websockets==8.1
xmltodict==0.12.0
zipp==3.6.0
zope.interface==4.7.1
```
## Server
It's a VM run in HyperV.

| Metric | Value |
| :----- | :---- |
| **hyperglass Version** | 1.0.4 |
| **hyperglass Path** | `/home/pablo/hyperglass` |
| **Python Version** | `3.6.15` |
| **Node Version** | `14.21.1` |
| **Platform Info** | `Linux-5.4.0-136-generic-x86_64-with-Ubuntu-20.04-focal` |
| **CPU Info** | Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz |
| **Logical Cores** | `4` |
| **Physical Cores** | `2` |
| **Processor Speed** | `2.394375GHz` |
| **Total Memory** | 8.28 GB |
| **Memory Utilization** | 12.1% |
| **Total Disk Space** | 24.63 GB |
| **Disk Utilization** | 42.5% |

## Client

- OS & Version: Ultramarine Linux 37, kern 6.0.17-300.fc37.x86_64
- Browser: Firefox

I would be grateful for any help or description.
Thanks in advance.
