### ISSUE TITLE
Devices.yaml invalid location error

### ISSUE THREAD

**Issue by mariokamenjak** [thatmattlove/hyperglass#223]
Hello, I am setting up our new hyperglass and adding devices to the devices.yaml file for the first time.

When testing with flask, I try to ping any address. but I get the following error:
router1 is an invalid location

I have tested the username and password and they work.

Here is my anonymized devices.yaml:

```
routers:
  - name: router1
    address: 1.5.2.1
    network:
      name: PRODUCTION
      display_name: AS65004
    credential:
      username: hyperglass
      password: correct
    port: 22
    nos: cisco_xr
    vrfs:
      - name: global
        default: true
        ipv4:
          source_address: 1.5.3.1
        ipv6:
          source_address: ::fffe::1
```

Surprisingly when I change name to name: New York City, NY , I don't get an invalid location but I get an authentication error(even though IP address and credentials are valid.
