### ISSUE TITLE
Support for configuring specific query types

### ISSUE THREAD

**Issue by KincaidYang** [thatmattlove/hyperglass#238]
Hi @thatmattlove , Does `v2.0.0` support configuring specific query types? For instance, I only wish to support `BGP Route` and `Traceroute`. I couldn't find any relevant documentation on this, and attempting to use the parameters from `v1.0.4` did not work.

**Comment by thatmattlove** [comment]
Yes, see these two pages:

https://v2.hyperglass.dev/configuration/directives

https://v2.hyperglass.dev/configuration/examples/add-your-own-command

It is possible you could filter the default directives to specific ones with something like:

```yaml
devices:
  - name: Name
    directives:
      - __hyperglass_juniper_bgp_route__
      - __hyperglass_juniper_traceroute__
```

I'm not 100% sure if that would work, I'll need to test it later. You can look [here](https://github.com/thatmattlove/hyperglass/tree/v2.0.0/hyperglass/defaults/directives) for all the built-in directives and their IDs.

**Comment by KincaidYang** [comment]
They don't seem to be working properly. When I configure them like this, all query types are still being built:
```yml
devices:
  - name: Amsterdam, NL
    address: 78.142.xxx.xxx
    platform: bird
    credential:
      username: bird
      password: xxxxxxxxxxxxxxxxxxxxxxxxx
    attrs:
      source4: 0.0.0.0
      source6: ::0
    directives:
      - __hyperglass_bird_bgp_route__
      - __hyperglass_bird_traceroute__
 ```
So I tried adding the parameter `builtins: false`, but after that, it didn't support any query type:
```yml
devices:
  - name: Amsterdam, NL
    address: 78.142.xxx.xxx
    platform: bird
    credential:
      username: bird
      password: xxxxxxxxxxxxxxxxxxxxxxxxx
    attrs:
      source4: 0.0.0.0
      source6: ::0
    directives:
      - builtins: false
      - __hyperglass_bird_traceroute__
      - __hyperglass_bird_bgp_route__
 ```
 
![image](https://github.com/thatmattlove/hyperglass/assets/91786638/1168d89c-fbd9-491e-8e3a-a63adf584b79)

**Comment by thatmattlove** [comment]
Ok. That was a guess, and I'm not surprised it didn't work. I will devise a way to selectively enable/disable built-in directives. In the mean time, you'll probably need to add your own custom directives.

**Comment by thatmattlove** [comment]
After looking at this in depth, this _does_ already exist, this is how you do it:

```yaml
devices:
  - name: Amsterdam, NL
    address: 78.142.xxx.xxx
    platform: bird
    credential:
      username: bird
      password: xxxxxxxxxxxxxxxxxxxxxxxxx
    attrs:
      source4: 0.0.0.0
      source6: ::0
    directives:
      - builtins: [traceroute, bgp_route] # no need to specify the full name of the directive
```

I'll update the docs.
