### ISSUE TITLE
v2.0.0 Vyos version platforms

### ISSUE THREAD

**Issue by ethamitc** [thatmattlove/hyperglass#245]
# Feature Description

Currently in Hyperglass, theirs 1 directive for VyOS, However between the versions of VyOS (1.3, 1.4, 1.5) the command formats change. It would be nice to specify the version of VyOS and allow hyperglass to use the commands applicable to that version.

Eg. devices.yaml
```yaml
platform: vyos_1.3
```

### Is your feature request related to a problem? Please describe.

By default, if you are not running the version of VyOS the commands we're build for, commands will fail. This wasn't a huge issue for me as I was able to just modify the vyos directive files and rebuild, but I feel like the user should be able to specify and just have it work.

**Comment by ServerForge** [comment]
I have not messed with 1.3 in quite awhile, i can dig up the syntax for it later, But this is the syntax i for VyOS 1.4 in the commands.yml, vrf should be "default" for the default vrf. 1.5 should be the same as 1.4 right now, but 1.5 could change later on but i wouldn't expect it to. 

```
  ipv4_default:
    bgp_route: "show bgp vrf {vrf} ipv4 {target}"
    bgp_aspath: "show bgp vrf {vrf} ipv4 regexp {target}"
    bgp_community: "show bgp vrf {vrf} ipv4 community {target}"
    ping: "ping {target} vrf {vrf} source-address {source} count 5"
    traceroute: "traceroute {target} vrf {vrf} source-address {source}"

  ipv6_default:
    bgp_route: "show bgp vrf {vrf} ipv6 {target}"
    bgp_aspath: "show bgp vrf {vrf} ipv6 regexp {target}"
    bgp_community: "show bgp vrf {vrf} ipv6 community {target}"
    ping: "ping {target} vrf {vrf} source-address {source} count 5"
    traceroute: "traceroute {target} vrf {vrf} source-address {source}"
```
