### ISSUE TITLE
Bring back VRF native support

### ISSUE THREAD

**Issue by kmisak** [thatmattlove/hyperglass#252]
# Feature Description

Previous versions of Hyperglass natively supports VRF, new one - not. It can be done with custom directives, but all pretty formatting of output is lost.
### Is your feature request related to a problem? Please describe.

Lot of networks use VRFs, removing support for the reduces Hyperglass big flexibility.
# Environment & Use Case

Any contemporary router supports VRFs
# Additional Context

**Comment by thatmattlove** [comment]
Try adding a custom directive and setting the following attribute:

```yaml
your-directive:
    name: BGP Route (VRF x)
    table_output: __hyperglass_juniper_bgp_route_table__
```

And on the device:

```yaml
devices:
    - name: your device
      platform: juniper
      directives:
          - your-directive
      structured_output: true
```

Supported values for table output are:

| `table_output`                                  | Platform |          Type |
| :---------------------------------------------- | -------: | ------------: |
| `__hyperglass_juniper_bgp_route_table__`        |  Juniper |     BGP Route |
| `__hyperglass_juniper_bgp_aspath_table__`       |  Juniper |   BGP AS Path |
| `__hyperglass_juniper_bgp_community_table__`    |  Juniper | BGP Community |
| `__hyperglass_arista_eos_bgp_route_table__`     |   Arista |     BGP Route |
| `__hyperglass_arista_eos_bgp_aspath_table__`    |   Arista |   BGP AS Path |
| `__hyperglass_arista_eos_bgp_community_table__` |   Arista | BGP Community |

If this works, I will come up with a way to make this more user friendly and add docs.

**Comment by kmisak** [comment]
Thank you for suggestion, but that doesn't work. Table output uses | display xml format as input, I tried to use that too - no luck.

Here is device sample:

routers:
  - name: mx-moscow
    address: 10.x.x.x
    group: AS49800
    credential:
      username: xxxx
      password: xxxxx
    port: 22
    platform: juniper
    driver: netmiko
    attrs:
      source4: x.x.x.x
      source6: x::x
    directives:
        - builtins: false
        - bgp_route_vrf
        - ping_vrf
        - traceroute_vrf
    structured_output: true

And directive:

bgp_route_vrf:
    name: BGP Route
    rules:
        - condition: 0.0.0.0/0
          action: permit
          command: "show route protocol bgp table AS49800.inet.0 {target} detail"
        - condition: ::/0
          action: permit
          command: "show route protocol bgp table AS49800.inet6.0 {target} detail"
    field:
        description: "IP Address, Prefix, or Hostname"
    table_output: __hyperglass_juniper_bgp_route_table__

**Comment by cameront-1** [comment]
Confirming this issue exists on Arista as well. Same instructions. Custom directives result in loss of pretty-formatting, instructing table/structured output has no effect

```
    platform: arista_eos
    directives:
       - test3
    structured_output: true
```

```
test3:
  name: BGPtest
  table_output: __hyperglass_arista_eos_bgp_route_table__
  rules:
    - condition: '0.0.0.0/0'
      ge: 4
      le: 32
      command: 'show ip bgp {target} vrf INTERNET | json'
```

Pre 2.0 vrf usage wasn't impacted.

**Comment by szferguson** [comment]
Following up on this, we tried adding the `__hyperglass_arista_eos_bgp_route_table__` directive and referencing this directive on each device.

**directives.yaml**
```
test3:
  name: BGPtest
  table_output: __hyperglass_arista_eos_bgp_route_table__
  rules:
    - condition: '0.0.0.0/0'
      ge: 4
      le: 32
      command: 'show ip bgp {target} vrf INTERNET | json'
```

**devices.yaml**
```
  - name: AMSCR6
    ...
    directives:
       - test3
    structured_output: true
```

However, the only way for the table to appear was adding `test3` in the `directives` tuple inside `bgp_route_arista.py`:
```
directives: t.Sequence[str] = (
    "__hyperglass_arista_eos_bgp_route_table__",
    "__hyperglass_arista_eos_bgp_aspath_table__",
    "__hyperglass_arista_eos_bgp_community_table__",
    "test3"
)
```
