### ISSUE TITLE
giant logo format

### ISSUE THREAD

**Issue by allanfrizzo** [thatmattlove/hyperglass#259]
when updating to version 2.0.2, the logo is too big,

![image](https://github.com/thatmattlove/hyperglass/assets/42051078/ab76cde2-3413-4982-b651-43028e90e98a)

**Comment by thatmattlove** [comment]
Have you tried using the [`width` parameter](https://hyperglass.dev/configuration/config/web-ui#logo)?

**Comment by allanfrizzo** [comment]
I'm using 100%

```
  logo:
    dark: /etc/hyperglass/static/images/eai-light.svg
    light: /etc/hyperglass/static/images/eai-dark.svg
    favicon: /etc/hyperglass/static/images/eai-favicon.png
    width: 100%
    height: null
```
