### ISSUE TITLE
CRITICAL | hyperglass.api.error_handlers:default_handler:48

### ISSUE THREAD

**Issue by saint-kid** [thatmattlove/hyperglass#262]
### Deployment Type

Docker

### Version

v2.0.2

### Steps to Reproduce

mikrotik v7
select bgp route and key in 8.8.8.8 click go

### Expected Behavior

routing info

### Observed Behavior

something went wrong

### Configuration

```yaml
site_title: XXX XXX
org_name: XXX XXX
```

### Devices

```yaml
devices:
   - name: XXX XXX
     address: XXX XXX
     credential:
       username: XXX XXX
       password: XXX XXX
     platform: mikrotik_routeros
     attrs:
       source4: XXX XXX
       source6: 2001:db8::1
```

### Logs

```console
yperglass-1  | 2024-06-15 15:06:50.219 | CRITICAL | hyperglass.api.error_handlers:default_handler:48 - Error
hyperglass-1  | 2024-06-15 15:06:50.221 | INFO     | logging:callHandlers:1762 - 10.10.100.21:43346 - "POST /api/query HTTP/1.1" 500
hyperglass-1  | INFO - 2024-06-15 15:06:50,222 - paramiko.transport - transport - Connected (version 2.0, client ROSSSH)
hyperglass-1  | INFO - 2024-06-15 15:06:50,290 - paramiko.transport - transport - Authentication (password) successful!
hyperglass-1  | 2024-06-15 15:06:51.713 | DEBUG    | hyperglass.plugins._manager:execute:186 - Output Plugin Starting Value
hyperglass-1  | 2024-06-15 15:06:51.713 | CRITICAL | hyperglass.api.error_handlers:default_handler:48 - Error
hyperglass-1  | 2024-06-15 15:06:51.715 | INFO     | logging:callHandlers:1762 - 10.10.100.21:43350 - "POST /api/query HTTP/1.1" 500
```
