### ISSUE TITLE
RPKI setting fails building UI

### ISSUE THREAD

**Issue by bbs2web** [thatmattlove/hyperglass#269]
### Deployment Type

Manual

### Version

v2.0.3

### Steps to Reproduce

/etc/hyperglass/config.yaml:
structured:
  rpki: external

### Expected Behavior

Should compile

### Observed Behavior

ValidationError: 1 validation error for Params
structured.rpki
  Input should be a valid dictionary or instance of StructuredRpki [type=model_type, input_value='external', input_type=str]

### Configuration

```yaml
org_name: Redacted
plugins: []
primary_asn: redacted
request_timeout: 90
site_description: Redacted Network Looking Glass
site_title: Redacted Network Looking Glass
cache:
  timeout: 15
  show_text: true
structured:
  rpki: external
web:
  dns_provider:
    name: cloudflare
  highlight:
   - pattern: blackhole
     label: Blackhole
     color: teal
   - pattern: unreachable
     label: Unreachable
     color: cyan
   - pattern: '192\.0\.2\.[0-9]+'
     label: Blackhole
     color: teal
   - pattern: 'fc00::192:0:2:[0-9a-f]+'
     label: Blackhole
     color: teal
  links:
   - title: PeeringDB
     url: https://www.peeringdb.com/asn/{primary_asn}
     side: left
     order: 0
   - title: Redacted
     url: https://www.redacted.com
     side: left
     order: 1
  location_display_mode: dropdown
```

### Devices

```yaml
Not applicable
```

### Logs

```console
Included in unexpected results above.
```
