### ISSUE TITLE
Target "My-IP" UI is covered by search button

### ISSUE THREAD

**Issue by mattpenn20** [thatmattlove/hyperglass#271]
### Deployment Type

Docker

### Version

v2.0.4

### Steps to Reproduce

1. Select a device and query type
2. Type anything in target (this can be erased or not, just need to do this to have search button appear)
3. Click "My IP"

### Expected Behavior

When My IP opens, it should be over top of the search magnifying glass icon button.
This is the case with all 3 browsers I tested (Chrome, Firefox, Edge)

### Observed Behavior

The search/magnifying glass button that appears in step 2 stays over top of the UI opened for My IP

### Configuration

```yaml
org_name: Beloved Hyperglass User
plugins: []
primary_asn: ######
request_timeout: 90
site_title: Looking Glass
logging:
    syslog:
        host: x
        port: 514
web:
    location_display_mode: dropdown
    logo:
        light: /etc/hyperglass/company-logo.svg
        dark: /etc/hyperglass/company-logo.svg
        favicon: /etc/hyperglass/company-icon.svg
        width: 100%
    theme:
        default_color_mode: light
```
