### ISSUE TITLE
Juniper structured throwing error

### ISSUE THREAD

**Issue by astlaurent** [thatmattlove/hyperglass#273]
### Deployment Type

Docker

### Version

v2.0.4

### Steps to Reproduce

When using structured on Juniper for show bgp route I am getting back

rt, 0, rt_entry, 0, peerAs

When I set structured to false it works fine. (log attached)

Also I noticed that if I set structured as false I see 2 versions of BGP route in the drop down, one does the non xml command, one does the xml command. I assume that is a bug of some sort (image attached of that)

[debug.txt](https://github.com/user-attachments/files/16195009/debug.txt)

![image](https://github.com/user-attachments/assets/38a1e8f4-8ec8-4da8-ab8c-923c955bfadc)

### Expected Behavior

router to produce expected results

### Observed Behavior

router did not product expected results

### Configuration

```yaml
org_name: TierPoint
plugins: []
primary_asn: 17378
request_timeout: 15
site_description: TierPoint Looking Glass
site_title: TierPoint Looking Glass

web:
    location_display_mode: dropdown
    text:
        title_mode: logo_only
    logo:
         light: /etc/hyperglass/static/custom/tierpoint-light.png
         dark: /etc/hyperglass/static/custom/tierpoint-dark.png
         favicon: /etc/hyperglass/static/custom/tierpoint-fav.png
         width: 50%
         height: null
    theme:
         default_color_mode: dark
    links:
    - title: tierpoint.com
      url: https://www.tierpoint.com
      side: right
      order: 1
    - title: PeeringDB
      url: https://www.peeringdb.com/asn/{primary_asn}
      side: left
      order: 2
    credit:
        enable: false

structured:
    rpki:
        mode: external
```

### Devices

```yaml
- name: Router
    group: North Central
    address: x.x.1.100
    credential: *credential1
    platform: juniper_junos
    attrs: *attr1
    directives:
        - builtins: [bgp_route, traceroute, ping]
```

### Logs

```console
attached
```
