### ISSUE TITLE
How it can get this output format

### ISSUE THREAD

**Issue by chacal1231** [thatmattlove/hyperglass#285]
### Deployment Type

Docker

### Version

v.2.0.4

### Steps to Reproduce

I'm looking the demo output and my output but need the demo output when client consult bgp route, now we on mikrotik_routeros, what device need for get that output?

### Expected Behavior

We want this
![image](https://github.com/user-attachments/assets/1170c9d2-b9ca-483a-b340-40885dc7577c)

### Observed Behavior

We got this output
![image](https://github.com/user-attachments/assets/8c25848e-78ec-4545-952f-aaafeb54240c)

### Configuration

```yaml
org_name: TVYMAS SAS
plugins: []
primary_asn: 273103
request_timeout: 90
site_title: TVYMAS LG
org_name: TVYMAS - Tools
web:
    logo:
        favicon: /etc/hyperglass/TVYMAS-bg-250.svg
    text:
        title: TVYMAS - Looking Glass
        subtitle: AS273103
        title_mode: text_only
    theme:
        colors:
            primary: "#d84b4b"
            secondary: "#118ab2"
    links:
        - title: PeeringDB
          url: https://www.peeringdb.com/asn/273103
          show_icon: true
          side: right
          order: 1
        - title: Website
          url: https://tvymas.co
          show_icon: false
          side: left
          order: 0
```

### Devices

```yaml
devices:
  - name: Bogota, Colombia
    address: 10.0.200.2
    credential:
      username: hyperglass
      password: hyperglass
    platform: mikrotik_routeros
    attrs:
      source4: 10.0.200.2
      source6: 2001:db8::1
```
