### ISSUE TITLE
[IOS XE] Doesn't work ping and Traceroute

### ISSUE THREAD

**Issue by jurandir-braz** [thatmattlove/hyperglass#289]
### Deployment Type

Docker

### Version

v2.0.4

### Steps to Reproduce

I followed some steps to try to make IOS XE work, removing the extensions from the cisco_xr.py file, but it doesn't work, hyperglass returns:

 Invalid input detected at '^' marker

### Expected Behavior

Ping OK
Traceroute OK

### Observed Behavior

                            ^
% Invalid input detected at '^' marker.

### Devices

```yaml
- name: BRA - RIO1
    address: 10.230.32.205
    credential:
      username: hglass_adm
      password: XXXXXXXXXX
    platform: cisco_xr
    attrs:
      source4: 189.125.2.146
      source6: 2001:db8::2
```

### Logs

```console
I don't know how to activate debug
```
