### ISSUE TITLE
Command gets passed to other directive

### ISSUE THREAD

**Issue by 33Fraise33** [thatmattlove/hyperglass#294]
### Deployment Type

Docker

### Version

v2.0.4

### Steps to Reproduce

Use the config below. When running the command: "Route" when entering ip 1.1.1.1 I get the error:
error: No routing tables matching specification.

This the error if I were to enter this ip in the command: "Route Table"

### Expected Behavior

command should be run for correct directive

### Observed Behavior

error: No routing tables matching specification.

### Configuration

```yaml
org_name: Citymesh
primary_asn: 199095
site_title: Citymesh - Looking Glass
web:
  location_display_mode: dropdown
  menus:
    - title: Help
      content: /etc/hyperglass/descriptions/help.md
      side: left
      order: 0
  links:
    - title: CM PeeringDB
      url: https://as199095.peeringdb.net/
      show_icon: false
      side: left
    - title: Netbox
      url: https://netbox.citymesh
      show_icon: false
      side: left
    - title: Juniper Grafana
      url: https://dashboard.citymesh
      show_icon: false
      side: left
```

### Devices

```yaml
devices:
  # Switches - Central Services - POP
  - name: CSBEZAVITXSW01
    group: 01 - Central Services - POP
    address: 10.11.255.20
    port: 1830
    credential:
      username: hyperglass
      key: /etc/hyperglass/juniper_key.pem
    platform: juniper
    directives:
      - builtins: false
      - show-route
      - show-route-table
```

### Logs

```console
DIRECTIVES:

## ROUTE
show-route:
  name: Route
  info: /etc/hyperglass/descriptions/route.md
  rules:
    - condition: 0.0.0.0/0
      command: show route {target}
    - condition: ::/0
      command: show route {target}
  field:
    description: ipv4 of ipv6 address

show-route-table:
  name: Route Table
  info: /etc/hyperglass/descriptions/table.md
  rules:
    - condition: ""
      command: show route table {target}
  field:
    description: VRF name
    options:
      - value: "inet"
        name: "Underlay"
      - value: "public"
        name: "Public VRF"
```
