### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by zunder1990** [thatmattlove/hyperglass#307]
### Deployment Type

Docker

### Version

v2.0.4

### Steps to Reproduce

Doing a bgp route quiry of 1.1.1.1 
get by respond of "Something went wrong."

### Expected Behavior

Why is the hyperglass user trying to go into enable  mode or python-shell modes.
"show ip bgp 1.1.1.1" work when I ssh to the router using the hyperglass user.

### Observed Behavior

na

### Devices

```yaml
devices:
  - name: ATL Core Router 1
    address: 162.255.xx.xx
    credential:
      username: hyperglass
      password: xxxxxxx
    platform: arista_eos
    attrs:
      source4: 162.255.xx.xx
      source6: "2605:7b80:xxx:xxxx::1"
  - name:  ATL Core Router 2
    address: 162.255.xx.xx
    credential:
      username: hyperglass
      password: xxxxxx
    platform: arista_eos
    attrs:
      source4: 162.255.xx.xx
      source6: "2605:7b80:xxxx:xxxx:2"
```

### Logs

```console
Arista logs
2024 Dec 16 12:06:34 EST cr1 Aaa: %AAA-4-CMD_AUTHZ_FAILED: User hyperglass failed authorization to execute command 'enable'
2024 Dec 16 12:06:44 EST cr1 Aaa: %AAA-4-CMD_AUTHZ_FAILED: User hyperglass failed authorization to execute command 'python-shell'
2024 Dec 16 12:24:04 EST cr1 Aaa: %AAA-4-CMD_AUTHZ_FAILED: User hyperglass failed authorization to execute command 'terminal width 511'
2024 Dec 16 12:25:21 EST cr1 Aaa: %AAA-4-CMD_AUTHZ_FAILED: User hyperglass failed authorization to execute command 'terminal width 511'

Arista config for user role
role hyperglass
   5 deny command ^conf.*
   10 permit command ^show ip bgp.*
   20 permit command ^show ipv6 bgp.*
   30 permit command ^ping.*
   40 permit command ^traceroute.*
   200 deny command .*

arista version Software image version: 4.30.3M
```
