### ISSUE TITLE
MikroTik Traceroute Issue on V7.16

### ISSUE THREAD

**Issue by mracar07** [thatmattlove/hyperglass#310]
### Deployment Type

Manual

### Version

v2.0.4

### Steps to Reproduce

When you run traceroute from mikrotik, its giving multiple outputs instead of just one full output.

<img width="713" alt="image" src="https://github.com/user-attachments/assets/4ae39a66-ff36-4249-8ab7-9afc9bcdd596" />

### Expected Behavior

But it should be outputting only the full output once

<img width="621" alt="image" src="https://github.com/user-attachments/assets/ac17e0eb-6236-4322-8457-a97170f86370" />

### Observed Behavior

When you run traceroute from mikrotik, its giving multiple outputs instead of just one full output.

<img width="713" alt="image" src="https://github.com/user-attachments/assets/4ae39a66-ff36-4249-8ab7-9afc9bcdd596" />

### Configuration

```yaml
org_name: Beloved Hyperglass User
plugins: []
primary_asn: 65000
request_timeout: 90
site_description: Beloved Hyperglass User Network Looking Glass
site_title: Beloved Hyperglass User
```

### Devices

```yaml
devices:
  - name: Istanbul / Atakoy TTN
    address: XXXXXXX
    credential:
      username: XXXXXXXXX
      password: XXXXXXXXX
    platform: mikrotik
    attrs:
      source4: IpV4
      source6: "::1"
```
