### ISSUE TITLE
Locations router1 & router2 have no Query Types in common.

### ISSUE THREAD

**Issue by micush** [thatmattlove/hyperglass#320]
### Deployment Type

Docker

### Version

v2.0.4

### Steps to Reproduce

Choose 3 routers from the list. The first two routers are of type cisco_ios and the third router is of type cisco_nxos. You then get the error 'Locations router1 & router2 have no Query Types in common' and cannot continue. If all three routers are of the same type it works fine.

### Expected Behavior

I expect it to work with different types of devices

### Observed Behavior

You get the error 'Locations router1 & router2 have no Query Types in common.'

### Configuration

```yaml

```

### Devices

```yaml
- name: switch1
    address: 192.168.1.1
    credential:
      username: admin
      password: ''
    platform: cisco_nxos
    attrs:
      source4: 192.168.1.1
      source6: fdf5::1
  - name: switch2
    address: 192.168.1.2
    credential:
      username: admin
      password: ''
    platform: cisco_ios
    attrs:
      source4: 192.168.1.2
      source6: fdf5::2
  - name: switch3
    address: 192.168.1.3
    credential:
      username: admin
      password: ''
    platform: cisco_ios
    attrs:
      source4: 192.168.1.3
      source6: fdf5::3
```

### Logs

```console

```
